# Generated by Django 4.2 on 2023-05-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplua',
            fields=[
                ('amplua_id', models.AutoField(primary_key=True, serialize=False)),
                ('amplua_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_surname', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_patronymic', models.CharField(max_length=100, null=True)),
                ('coach_info', models.CharField(max_length=100)),
                ('coach_birthdate', models.DateField()),
                ('coach_image', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KubanTeam',
            fields=[
                ('kubanteam_id', models.AutoField(primary_key=True, serialize=False)),
                ('kubanteam_image', models.CharField(max_length=100, null=True)),
                ('kubanteam_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('opponent_id', models.AutoField(primary_key=True, serialize=False)),
                ('opponent_name', models.CharField(max_length=100)),
                ('opponent_image', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_surname', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('player_patronymic', models.CharField(max_length=100, null=True)),
                ('player_number', models.CharField(max_length=100)),
                ('player_birthdate', models.DateField()),
                ('player_height', models.CharField(max_length=100)),
                ('player_image', models.CharField(max_length=100, null=True)),
                ('amplua_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.amplua')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=100)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('playerseason_id', models.AutoField(primary_key=True, serialize=False)),
                ('playerseason_playerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.player')),
                ('playerseason_seasonid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_scoreopponent', models.PositiveIntegerField()),
                ('match_scorekuban', models.PositiveIntegerField()),
                ('match_date', models.DateField()),
                ('match_kuban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.kubanteam')),
                ('match_opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.opponent')),
            ],
        ),
        migrations.CreateModel(
            name='CoachSeason',
            fields=[
                ('coachseason_id', models.AutoField(primary_key=True, serialize=False)),
                ('coachseason_coachid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.coach')),
                ('coachseason_seasonid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.season')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='role_coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.role'),
        ),
    ]
